### PR TITLE
Feat: Add Excluded Dates formset to Semester form: Closes: #1057

### PR DESCRIPTION
**Pull request by 9921622**

### CODE REVIEW

**Review by tylerecouture — CHANGES_REQUESTED** [review]
Wow, nice work!!  This is a huge one and hopefully you learned a ton figuring this out! A few things I noticed.  

1. The mobile formatting is bad:

image
So I'd suggest not putting them in seperate bootstrap columns, so they don't break.  Same with the label field, it will all fit on the smallest screen so no need to bootstrap wrapping.

2. You didn't pull before this PR?  You are a few commits behind
3. The optional `label` field on the ExcludedDate model is missing on the formset, (which you currently don't have because your code is out of date; you added that field on 11 July)

**Comment by 9921622** [comment]
added request changes

**Comment by 9921622** [comment]
added discussed changes

full screen:
image

small screen:
image

**Review by tylerecouture — CHANGES_REQUESTED** [review]
If I enter a label without a date:

image

This needs to be caught in a test, and corrected.

**Comment by 9921622** [comment]
added requested changes + 

small screen now doesnt have buttons clip the scrollbar
image

**Review by tylerecouture — APPROVED** [review]

**Pull request merged**
