### PR TITLE
1476 Submission quest feature merge resolve

### PR DESCRIPTION
**Pull request by 9921622**
Please ensure you are familiar with our Pull Request Description expectations described here: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
### What?
There were some issues with #1476 and a couple of bugs.

### Why?
See #1627

### How?
Rebased with develop branch and resolved conflicts. 

There was an issue with quick reply form where after the user has submitted, and makes a comment via quick reply. They get a 404.

Fixed another issue where admin was creating a draft comment for a user when going to submission view (and making the owner of the draft comment admin)

#### manual tests
+ user comment submission 
+ user comment after submission (quick reply)
+ admin comment before approving (quick reply)
+ admin approve comment (quick reply)
+ user comment after approve (quick reply)
+ user comment using submission view
+ user comment using submission view (2nd time)
+ test if draft was deleted when submission is deleted
+ manually test the migration from draft_text to draft_comment in submission view 

#### automated tests
+ checks the functionality of multiple comments using standard and quick reply view

### Anything Else?
added a pre delete signal to QuestSubmission deleting any comments linked to it when QuestSubmission is deleted.
Also included a test for it

### Review request
@tylerecouture

## Summary by CodeRabbit

- **New Features**
  - Added the `draft_comment` field to `QuestSubmission` to store submission comments.

- **Bug Fixes**
  - Updated `mark_completed` method to manage the new `draft_comment` field properly.

- **Tests**
  - Added tests to check the association of comments with `QuestSubmission`.
  - Introduced tests to validate the `pre_delete` signal functionality for `QuestSubmission`.

- **Chores**
  - Implemented a signal handler to delete comments linked to a `QuestSubmission` upon its deletion.

### CODE REVIEW

**Comment by 9921622** [comment]
@tylerecouture

**Comment by tylerecouture** [comment]
@9921622 

A couple questions:

1. How does this handle existing comment data? Please remind me.  We need to ensure it can gracefully handle a transition between the two systems 

2."Theres an issue were deleting submissions with comments still attached does not delete comments. Thus leaving unlinked comments."

A couple possible solutions: 
a. Delete them in a submission pre-delete signal
B. Change the foreign key to use on delete cascade(?)

**Comment by 9921622** [comment]
@tylerecouture added a pre delete signal. 

Also I added what i did in #1627 

>> Nothing happens to existing comments. Except for Submissions with comment drafts disappear and the text in the drafts are lost. (expected behavior)

**Comment by 9921622** [comment]
@tylerecouture can you review this?

**Comment by tylerecouture** [comment]
@9921622 will try to review this afternoon.

**Comment by 9921622** [comment]
did a lot of changes. So this pr is kind of irrelevant now

**Comment by tylerecouture** [comment]
Ok. Why so many changes? Just make sure you still keep an interim step for us to use equivalent to this.  We won't be implementing the feature into production all at once. First will be just swapping out the comment model like this PR

**Comment by 9921622** [comment]
ok ill put open it back. I turned the `def complete` fbv to a cbv and thought I made all these changes irrevlant. Forgot I changed more than that.

**Comment by tylerecouture** [comment]
If you can just cherry pick your commit with the def complete refactor, that would be good to have here?

**Comment by tylerecouture** [comment]
But that assumes you have nicely separated logical commits, in reality I know that rarely happens in practice, so if you can't, no worries.

**Comment by tylerecouture** [comment]
@9921622 Can you rename this? "Merge Resolve" is ambiguous, and "fixes" is for bugs, use "closes" instead for feature or non-bug issues, since you're not fixing anything.  Clear Commit messages and PR names are important.

**Comment by 9921622** [comment]
@tylerecouture done

**Comment by tylerecouture** [comment]
@9921622 Still ambiguous. And despite the merge, this is now the main PR, so it's the feature, the merge is just one fo the commits (that will be squashed). Remember this is what our git log, or git graph is going to show.  How about "Replace submission draft_text with draft_comment for new Q&A feature; Closes #1627"

**Comment by 9921622** [comment]
@tylerecouture done. but i dont think the other pr is squished, I can still see what was changed with the other pr

image
image

**Comment by tylerecouture** [comment]
> @tylerecouture done. but i dont think the other pr is squished, I can still see what was changed with the other pr
> 
> image
> image
> 

On your branch, yes, but when it's merged into develop I squash them (usually because there are tin of little poorly named commits in PRs...haha)

**Comment by tylerecouture** [comment]
Actually, is there a difference between the PR name? Or does it just use the last commit?

**Comment by 9921622** [comment]
@tylerecouture not sure what you mean.
If you're squashing two commits together dont you get to choose which pr name to use?

like this in a git squash tutorial on youtube
image

**Comment by tylerecouture** [comment]
It's a combined all in one auto-magical thing github does: 
image

**Pull request merged**
