### PR TITLE
create teams upon tenant initialization; closes #1056

### LINKED ISSUE #1056: Add new default badge type: Groups, with 3 default new badges
A default BadgeType called Groups, with an appropriate font awesome icon.

Test for each can be simple: "You are a member of the Red team!" etc

Then add three new default badges within that group, Red Team, Green Team and Blue Team.  Can use these icons and include in repo.
red_team
green_team
blue_team

Related to #923

### PR DESCRIPTION
**Pull request by Dylan-RG-Patterson**
image
created the teams badge type and 3 accompanying badges, which can act as ways to sort students into groups for collaboration or special access to site features. additionally, default icons for badges and quests have been reformatted such that they are now completely functional in development.

### CODE REVIEW

**Comment by Dylan-RG-Patterson** [comment]
this is a very uncool build and test failure i was sure my test suite ran ok before pushing i will re-evaluate this

**Comment by Dylan-RG-Patterson** [comment]
ok test suite runs fine on my end time to see if this is a git-isolated issue

**Review by tylerecouture — CHANGES_REQUESTED** [review]
Tests failing.

**Comment by Dylan-RG-Patterson** [comment]
since a different branch was pushed with the correct update, I think it's best to just close this PR.

**Pull request closed without merging**
