### PR TITLE
Teacher and student get different text in courses tab in profile detail; Closes #953

### LINKED ISSUE #953: Staff shouldn't be prompted to join a course
On the Profile page of Staff:
image

The "join a course" message and button should be removed.

### PR DESCRIPTION
**Pull request by 9921622**
Teacher with no courses:
image

Teacher with courses (via /admin/)
image

Student with no courses
image

### CODE REVIEW

**Review by tylerecouture — CHANGES_REQUESTED** [review]
Great PR.  Your test has a great docstring and is awesomely commented.  This is exactly what I'd like to see.

However, seeing the result I would like two changes:

1. Even if a staff member DOES have a course, it should still say "Not applicable to staff users".
2. Please remove the edit button in these cases also

**Comment by 9921622** [comment]
applied the changes

staff
image
student
image

**Comment by tylerecouture** [comment]
@9921622 can you confirm that the "Add" button still appears when a staff member is viewing a student's profile?  I think so, but want to make sure because it isn't in your tests.

**Review by tylerecouture — COMMENTED** [review]
Can you confirm that the "Add" button still appears when a staff member is viewing a student's profile? I think so, but want to make sure because it isn't in your tests.

**Comment by 9921622** [comment]
Add button still appears when viewing student profile with staff account
image

**Pull request merged**
