### PR TITLE
Fix: generate_quests also generates campaigns; Closes #1014

### LINKED ISSUE #1014: Modify generate_quests to include campaigns
When creating a new development environment, the `generate_content` shell command is used to create some default data (100 students and some groups of quests)

However, the 5 "campaigns" of 10 quests each, don't actually get put into a real campaign (Category model)

Modify the `generate_quests`method so that it actually creates some Category objects (campaigns) and puts the generated quests into them.  Can use the name generator to give the campaign unique names.

Make sure to modify `test_generate_quests` to do a check that those campaigns were created.

### PR DESCRIPTION
**Pull request by 9921622**
Please ensure you are familiar with our Pull Request Description expectations described here: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
### What?
Modified the ```generate_quest``` command to use campaigns.
Its previous behaviour did not link quests to any campaigns.

using the ```tenant_shell```
```
(bytedeck) D:\#\BYTEDECK_FORK\bytedeck\src>python manage.py tenant_command shell
Enter Tenant Schema ('?' to list schemas): testtenant2
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from hackerspace_online.shell_utils import generate_content

In [2]: generate_content()
Generating content...
Campaign-clammy-tan-discus
        stealthy-wheat-seal
        zippy-black-terrier
        jumpy-salmon-reindeer
        grumpy-jade-octopus
        skanky-turquoise-anteater
        beady-jade-uakari
        cheeky-teal-hamster
        ugly-periwinkle-orangutan
        snoopy-vermilion-setter
        craggy-plum-impala
Campaign-stuffy-alizarin-jackal
        grumpy-ochre-lobster
        gloppy-amethyst-bloodhound
        crappy-champagne-lizard
        blurry-brown-raccoon
        snippy-buff-affenpinscher
        pasty-purple-dragonfly
        thirsty-mauve-dragonfly
        hazy-aquamarine-stoat
        pokey-celadon-whale
        ready-tomato-penguin
Campaign-hilly-rose-eel
        shabby-cream-mastiff
        freaky-zucchini-spoonbill
        pokey-malachite-gecko
        clammy-rust-alligator
        slaphappy-yellow-drever
        crappy-sepia-kiwi
        pokey-pumpkin-urchin
        bumpy-ivory-zebra
        shaky-viridian-devil
        craggy-violet-chameleon
Campaign-geeky-cream-hippopotamus
        jumpy-yellow-spider
        randy-rose-cuscus
        cozy-emerald-fossa
        lanky-grey-mist
        slaphappy-maroon-eleuth
        stuffy-lemon-robin
        gimpy-jade-crocodile
        trippy-lavender-ibis
        lumpy-myrtle-spaniel
        smelly-scarlet-shark
Campaign-snappy-copper-bulldog
        gimpy-buff-flamingo
        muzzy-razzmatazz-spoonbill
        pretty-turquoise-eagle
        tacky-chartreuse-stoat
        clammy-flax-liger
        baggy-maroon-axolotl
        paltry-teal-mongoose
        nippy-amethyst-birman
        lousy-magnolia-chicken
        clammy-bronze-frigatebird
50 Quests generated in 5 campaigns.


Generating 100 students:
lisa.kessinger
anthony.jacobson
kristy.lowery
debbie.parshall
ronald.harmon
nikki.rippy
pamela.blanchard
alissa.cox
james.valdez
freddie.beyett
lana.andersen
chester.lunde
christine.rauch
evangeline.strawderman
alfred.broker
cecil.immediato
mariela.budge
ralph.tusing
robert.rodriguez
lorraine.cantrell
joshua.smith
dana.mahi
shirley.desantis
ida.harrison
james.moser
dennis.snellgrove
tara.dixon
nicholas.ramirez
roy.weston
leo.williams
camille.mullane
kathleen.jordan
pat.glahn
george.fraser
jennifer.hockenberry
andrew.durham
christopher.isbell
david.bonaccorsi
gary.hutchins
cassandra.aucoin
richard.roseberry
rebecca.herring
charles.rodriguez
william.blackwell
jana.lyster
michelle.price
jerry.poulin
barbara.william
kai.miller
john.bufkin
carmon.boyda
scott.spencer
russell.chavez
asa.holling
dawn.green
arthur.campbell
daniel.mallory
james.garcia
jerry.valentin
cole.simmons
carole.traylor
katherine.robinson
robert.oliveira
robert.thibodeau
patrick.ortiz
james.perkins
thomas.karst
clementina.thomas
mildred.abrams
dan.costello
joshua.lovelace
glenn.villegas
cedric.corbin
theresa.pineda
angel.carpenter
jose.lemmons
jeff.clapp
ellen.wiggins
david.whisenand
lori.cilley
mark.leiva
susan.spillman
david.fehlinger
kyle.boyce
rebecca.lybert
adolfo.rodriguez
tracy.venegas
david.harris
leda.ballard
wilson.coulter
adrienne.adams
michael.hunter
maurice.saunders
matthew.davis
karen.rivera
john.tucker
robert.caldwell
cliff.lebovic
brian.lee
valerie.davis

100 students generated.
```

### Why?
See #1014

### How?
Generated a campaign with a unique name using the same method for quests.
Updated docstring.
Updated tests to reflect this.

### Testing?
only modifed the ```test_generate_quests``` to test for campaigns

### Screenshots (if front end is affected)
after running the command
image
image
image

### Anything Else?
I noticed that nothing was printing the ```initial_quest``` so i added that.
Adding indents to the print output. so its easier to read when ```quiet=False```

### Review request
@tylerecouture

## Summary by CodeRabbit

- **New Features**
  - Enhanced campaign generation with additional quests, allowing for more detailed and varied gameplay experiences.

- **Tests**
  - Updated test cases to reflect changes in quest and campaign generation, ensuring robust validation of new features.

### CODE REVIEW

**Comment by 9921622** [comment]
@tylerecouture review

**Review by tylerecouture — COMMENTED** [review]
Thanks for improving the docstrings.

Can you run this, paste the output into the PR description, then also paste a screenshot of the map that gets generated from it?

**Comment by 9921622** [comment]
done

**Comment by tylerecouture** [comment]
The map shows it didn't work. Only the first quest is in the campaign.

**Comment by tylerecouture** [comment]
image

**Comment by 9921622** [comment]
noted. going to add a test for that as well

**Comment by 9921622** [comment]
@tylerecouture ok should be good now.

Also made the output of ```generate_content``` a bit more readable with indents when ```quiet=False```

**Pull request merged**
