### PR TITLE
Fix: Tag detail view shows duplicate ordinal for repeatable quests; Closes #1210

### LINKED ISSUE #1210: Tag detail view shows duplicate ordinal for repeatable quests
image

### PR DESCRIPTION
**Pull request by 9921622**
Please ensure you are familiar with our Pull Request Description expectations described here: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
### What?
Fixed an issue where ordinality appears twice in student TagDetailView but only for repeat quests.

### Why?
This issue is a formatting error. Ordinal values showing up twice is unexpected behaviour
See #1210

### How?
The issue was that ordinal value is added to the quest name if its a repeat quest. While the DetailView does the same thing in the html via template tags.

The solution is to use the ```QuestSubmission.__str__``` value by itself
```
Original code
+ Quest (1)
+ Quest (2) (2)  # Quest (2) is the __str__ value of the quest submission
Solution using __str__ by itself
+ Quest  # ordinality does not show up but is expected behaviour
+ Quest (2)
```

I fixed it by removing the html template tag that adds the extra ordinal values. Hence removing the extra "(2)", "(3)", etc.
image

### Testing?
Added test case for checking correct ordinality.
image

### Screenshots (if front end is affected)
screen shot of what the test case looks like
image

### Anything Else?
None

### Review request
@tylerecouture

### CODE REVIEW

**Comment by 9921622** [comment]
@tylerecouture review

**Comment by tylerecouture** [comment]
Description WHY doesn't include link to issue.  Please link.

**Review by tylerecouture — CHANGES_REQUESTED** [review]
1. Please link to issue in WHY section of PR description
2. Please expand on this, It's not clear to me what you are saying.  Also are you pretty sure?  if you are only pretty sure, please verify.

**Comment by 9921622** [comment]
alright. updated the wording and linked the issue in the "WHY" lmk if it needs more clarity

**Comment by tylerecouture** [comment]
@9921622 Can you clarify what this means? "...and its the first one."  The first what?

**Comment by tylerecouture** [comment]
@9921622 also, are you not able to track down the issue?  Why are you not certain that this is the problem?  If you aren't certain it's the problem, then we can't be certain this will fix it... haha

**Comment by 9921622** [comment]
i know the issue is the ordinal naming scheme. 
Here's how it's implemented:
```QuestSubmission```
image
```QuestSubmissionManager ```
image

But it doesn't look like a bug. just a naming convention for multiple submissions of the same quest.

**Comment by 9921622** [comment]
also updated the wording for the "...and its the first one."

**Comment by 9921622** [comment]
@tylerecouture

**Comment by 9921622** [comment]
updated the pr so DetailView follows the same ordinal naming conventions as Quests Tab in ProfileView
image

**Comment by 9921622** [comment]
@tylerecouture

**Comment by 9921622** [comment]
wait i now have 2 commits

**Comment by 9921622** [comment]
@tylerecouture since you added a merge branch can i assume its good to go?

**Pull request merged**
