### PR TITLE
Feat: CodeRabbitAI review instructions; Closes #1626

### LINKED ISSUE #1626: coderabbitai review instructions
Generate some instructions for our ai reviewer (via its config file).

Example:

https://docs.coderabbit.ai/guides/review-instructions/

Does some web research of some good things we can suggest.  Here are some initial thoughts (may require rewording for the config instructions, I don't know the format they want):

- Always suggest docstrings for methods, and try to improve existing docstrings
- Don't suggest type annotations
- Suggest more efficient Django querysets

### PR DESCRIPTION
**Pull request by 9921622**
Please ensure you are familiar with our Pull Request Description expectations described here: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
### What?
Added some review instructions for CodeRabbitAI

### Why?
See #1626 

### How?
added `path_instructions` to for all `.py` files.
Tried to "optimize" the prompts based on prompting guide for chatgpt. (Coderabbit uses gpt models) 
https://platform.openai.com/docs/guides/prompt-engineering/strategy-write-clear-instructions

### Testing?
Adding an extra instruction indicating Coderabbit that all revews of `.py` files need to have "THIS IS A TEST" 3 times. To show the instructions are affecting CodeRabbit's output.
(Note: these prompts are now outdated)
image
added a dummy function to one of the `.py` files
image

`.py` file
image
non `.py` file
image

### Anything Else?
+ added extra stuff for coderabbit.
  + full clean after every `model.save()` refrencing this [issue](https://github.com/bytedeck/bytedeck/issues/1630)
  + no ["Catch all" try except blocks](https://github.com/bytedeck/bytedeck/pull/1617#discussion_r1647926519)
  + stop asking for security risks in test files  (https://github.com/bytedeck/bytedeck/pull/1632#discussion_r1655499498 and https://github.com/bytedeck/bytedeck/pull/1632#discussion_r1655499503)
  + Avoid adding comments to [import modules](https://github.com/bytedeck/bytedeck/pull/1617#discussion_r1639051633)

### Review request
@tylerecouture 

## Summary by CodeRabbit

- **New Features**
  - Introduced a new method `test_new_model()` in the `QuestManager` class for testing purposes.

- **Chores**
  - Updated code review configuration to enhance docstrings, optimize Django querysets, ensure model validation, avoid generic exception handling in tests, and discourage certain import comments.

### CODE REVIEW

**Comment by 9921622** [comment]
@coderabbitai

**Comment by 9921622** [comment]
@coderabbitai review

**Comment by 9921622** [comment]
@tylerecouture review

**Comment by 9921622** [comment]
actually maybe leave this pr and I can add more instructions for things coderabbit can ignore

**Review by tylerecouture — CHANGES_REQUESTED** [review]
This is excellent.  Thank you for posting those other rabbitai responses. I think we should mostly listen to coderabbit.  In some cases, it's hallucinating, but in many cases, it's suggesting best practices we haven't been following on this project because it's so old, but we should.  So we should investigate why it's making these suggestions (both by asking it, and by doing your own parallel research)

They are just screenshot so I can't reply to them directly, but here is what I would do:

- hardcoded passwords in tests:  We probaby shouldn't because we don't know if django handles them differently, and the real passwords are secure, so we should test that way.  It might be worth asking codrabbitai "Why shouldn't we use hardcoded passwords in tests?"
- Try Except around database interactions.  That sounds reasonable, but I don't actually know what database interaction it's taking about in that image. Ask coderabbit AI for clarification and more details.
- full_clean().  Dang, I went down a bit of a rabbit hole with this one.  And yes, we should be! I created a new issue for you on this. Thank you for posting it!
- catch-all try block, definitely not good, so tell it to suggest precise except statements when suggesting a try block.

**Comment by 9921622** [comment]
another one we should block.
"We are not handling sensitive information in tests. It is all procedural."
image
image

**Comment by 9921622** [comment]
@tylerecouture for the hardcoded passwords part. Coderabbitai just gave me gpt jargon. Unless we are specifically testing the security of passwords we can probably ignore this
```
It's a good practice to simulate as close to a production setup as possible in test environments, which includes the use of secure password handling methods.
```
https://github.com/bytedeck/bytedeck/pull/1617#discussion_r1655606395

**Comment by tylerecouture** [comment]
> @tylerecouture for the hardcoded passwords part. Coderabbitai just gave me gpt jargon. Unless we are specifically testing the security of passwords we can probably ignore this
> 
> ```
> It's a good practice to simulate as close to a production setup as possible in test environments, which includes the use of secure password handling methods.
> ```
> 
> [#1617 (comment)](https://github.com/bytedeck/bytedeck/pull/1617#discussion_r1655606395)

I think this is a good suggestion and we should do it in this case.

**Review by tylerecouture — APPROVED** [review]

**Pull request merged**
