### PR TITLE
Fix: expired quests in 'quests:available' appear at the top; Closes #1430

### LINKED ISSUE #1430: Quest list sort order funkiness
Recent queryset optimizations probably messed with the default sort order. Currently expired(?) quests appear at the bottom instead of the top:

image

### PR DESCRIPTION
**Pull request by 9921622**
Please ensure you are familiar with our Pull Request Description expectations described here: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/
### What?
Expired quests appear at the bottom of `'quests:available'`. This is unexpected behavior and this pr fixes it

### Why?
See #1430

### How?
Changed the meta fields around to make `expired_dates` and `time_expired` be sorted in ascending order.
While `time_expired` is sorted after `expired_dates`.

Making the order be `expired_dates` -> `time_expired` -> `names`.
ie. 
```
2000-1-1
2000-1-2 0:00
2000-1-2 1:00
```

### Testing?
Added a new test case `QuestListViewTest.test_available_quest_list_ordering__expired_quests` which tests the expected order of expired quests. 

### Screenshots (if front end is affected)
image

### Review request
@tylerecouture

## Summary by CodeRabbit

- **New Features**
	- Improved the "Available Quests" list by ordering expired quests before non-expired ones for better user experience.
	- Enhanced sorting logic by treating quests with null expiration dates as having a far future date.
	- Updated default quest ordering to prioritize `sort_order`, `date_expired`, `time_expired`, and `name`.

- **Tests**
	- Added test to ensure expired quests are correctly ordered before non-expired quests in the "Available Quests" list.

### CODE REVIEW

**Comment by 9921622** [comment]
@tylerecouture review

**Review by tylerecouture — CHANGES_REQUESTED** [review]
Can you investigate why the existing sort order in Meta isn't working?

image

**Comment by 9921622** [comment]
yeah im not sure why I ignored the meta fields. there might have been a reason but i dont remember why.

**Comment by 9921622** [comment]
@tylerecouture review

**Review by tylerecouture — CHANGES_REQUESTED** [review]
Looking good, just need to resolve the conflict

**Pull request merged**
