### PR TITLE
Search quest using campaign name; Closes #545

### LINKED ISSUE #545: Fitler quests by campaign
Easier to select an entire campaign for export or deletion

image

### PR DESCRIPTION
**Pull request by 9921622**
Ability to use the search box to filter quests by their associated campaign

image

### CODE REVIEW

**Comment by tylerecouture** [comment]
@9921622 this still has those 2 ghost commits for some reason.  Good practice for you =)  Can resubmit this without them?

**Review by tylerecouture — CHANGES_REQUESTED** [review]
this still has those 2 ghost commits for some reason. Good practice for you =) Can resubmit this without them?

**Comment by tylerecouture** [comment]
@9921622  one this you can try is to rebase your changes onto the current develop branch.  Either google how to do this or.... I think you just do this: have this branch checked out (bugfix545v4 ?), right click the develop branch in VS Code graph and chose "rebase onto".  THat might work? but might not because I'm just guess what your doing.  If it doesn't work, can you send me a screenshot of your git graph in vscode?

**Comment by 9921622** [comment]
finally remove the ghost commitss. resubmitting pr

**Pull request closed without merging**
